# Generated by Django 4.1 on 2022-09-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='blog/files/%Y_%m_%d/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='blog/images/%Y_%m_%d/'),
        ),
    ]
